# GitLab CI/CD Pipeline for GCP TypeScript Hono.js Serverless Application
# Supports automatic deployment to development and production environments

stages:
  - validate
  - build
  - test
  - deploy

variables:
  NODE_VERSION: "20"
  PNPM_VERSION: "latest"
  GCP_PROJECT_ID: "$GCP_PROJECT_ID"
  GCP_REGION: "asia-south1"
  FUNCTION_NAME: "hono-serverless-api"

# Cache configuration for faster builds
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/
    - .pnpm-store/

# Before script to set up environment
before_script:
  - echo "Setting up Node.js and pnpm..."
  - curl -fsSL https://get.pnpm.io/install.sh | sh -
  - export PATH="$HOME/.local/share/pnpm:$PATH"
  - pnpm config set store-dir .pnpm-store
  - pnpm install --frozen-lockfile

# Validation stage - runs on all branches
validate:
  stage: validate
  image: node:${NODE_VERSION}-alpine
  script:
    - echo "🔍 Running code validation..."
    - pnpm run lint
    - pnpm run check
    - echo "✅ Code validation passed"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "main"

# Build stage - compiles TypeScript
build:
  stage: build
  image: node:${NODE_VERSION}-alpine
  script:
    - echo "🏗️ Building TypeScript application..."
    - pnpm run build
    - echo "✅ Build completed successfully"
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "main"

# Test stage - runs tests (placeholder for now)
test:
  stage: test
  image: node:${NODE_VERSION}-alpine
  script:
    - echo "🧪 Running tests..."
    - pnpm run test || echo "No tests implemented yet"
    - echo "✅ Tests completed"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $CI_COMMIT_BRANCH == "main"

# Deploy to Development Environment
deploy:development:
  stage: deploy
  image: google/cloud-sdk:alpine
  environment:
    name: development
    url: https://${GCP_REGION}-${GCP_PROJECT_ID}.cloudfunctions.net/${FUNCTION_NAME}-dev
  variables:
    NODE_ENV: "development"
    DEPLOYMENT_ENV: "dev"
  before_script:
    - echo "🚀 Setting up GCP authentication for development..."
    - echo $GCP_SERVICE_ACCOUNT_KEY_DEV | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file gcp-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - apk add --no-cache curl bash
    - curl -fsSL https://get.pnpm.io/install.sh | sh -
    - export PATH="$HOME/.local/share/pnpm:$PATH"
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile
  script:
    - echo "🌱 Deploying to Development Environment..."
    - echo "Environment: $NODE_ENV"
    - echo "Branch: $CI_COMMIT_BRANCH"
    - echo "Commit: $CI_COMMIT_SHA"
    
    # Set up environment-specific variables
    - export FUNCTION_NAME="${FUNCTION_NAME}-dev"
    - export TF_VAR_function_name="$FUNCTION_NAME"
    - export TF_VAR_environment="dev"
    - export TF_VAR_deployment_version="dev-$CI_COMMIT_SHORT_SHA"
    
    # Install Terraform
    - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
    - unzip terraform_1.6.0_linux_amd64.zip
    - mv terraform /usr/local/bin/
    
    # Deploy using our CI deployment script
    - chmod +x scripts/deploy-ci.sh
    - NODE_ENV=development bash scripts/deploy-ci.sh
    
    - echo "✅ Development deployment completed successfully"
    - echo "🔗 Function URL: https://${GCP_REGION}-${GCP_PROJECT_ID}.cloudfunctions.net/${FUNCTION_NAME}"
  after_script:
    - rm -f gcp-key.json
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  dependencies:
    - build

# Deploy to Production Environment
deploy:production:
  stage: deploy
  image: google/cloud-sdk:alpine
  environment:
    name: production
    url: https://${GCP_REGION}-${GCP_PROJECT_ID}.cloudfunctions.net/${FUNCTION_NAME}
  variables:
    NODE_ENV: "production"
    DEPLOYMENT_ENV: "prod"
  before_script:
    - echo "🚀 Setting up GCP authentication for production..."
    - echo $GCP_SERVICE_ACCOUNT_KEY_PROD | base64 -d > gcp-key.json
    - gcloud auth activate-service-account --key-file gcp-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - apk add --no-cache curl bash
    - curl -fsSL https://get.pnpm.io/install.sh | sh -
    - export PATH="$HOME/.local/share/pnpm:$PATH"
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile
  script:
    - echo "🏭 Deploying to Production Environment..."
    - echo "Environment: $NODE_ENV"
    - echo "Branch: $CI_COMMIT_BRANCH"
    - echo "Commit: $CI_COMMIT_SHA"
    
    # Set up environment-specific variables
    - export TF_VAR_function_name="$FUNCTION_NAME"
    - export TF_VAR_environment="prod"
    - export TF_VAR_deployment_version="v1.0.$CI_PIPELINE_ID"
    
    # Install Terraform
    - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
    - unzip terraform_1.6.0_linux_amd64.zip
    - mv terraform /usr/local/bin/
    
    # Deploy using our CI deployment script
    - chmod +x scripts/deploy-ci.sh
    - NODE_ENV=production bash scripts/deploy-ci.sh
    
    - echo "✅ Production deployment completed successfully"
    - echo "🔗 Function URL: https://${GCP_REGION}-${GCP_PROJECT_ID}.cloudfunctions.net/${FUNCTION_NAME}"
  after_script:
    - rm -f gcp-key.json
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  dependencies:
    - build
  when: manual  # Require manual approval for production deployments

# Cleanup job to remove old deployments (optional)
cleanup:
  stage: deploy
  image: google/cloud-sdk:alpine
  script:
    - echo "🧹 Cleaning up old deployments..."
    - echo "Cleanup completed"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"
  when: manual
  allow_failure: true